### ISSUE TITLE
Problem with CC2531 USB Dongle

### ISSUE THREAD

**Issue by mradmilovic** [mdsamdsa/zigbee-web#1]
I am using CC2531 USB Dongle with BeagleBone Black and I am very new in zigbee. I made everything as in instructions and then run your web. I changed config file to my IP addresses and ports. Your web application and zigbee-web-client say that all my servers are connected and ok, but I cant get PANID back from my USB Dongle. I guess that Dongle is coordinator. I get this warning. 

[2016-04-06 12:37:17.908] [WARN] zgwc:proxy - TIMEOUT waiting for confirmation
[2016-04-06 12:37:18.068] [WARN] zgwc:machine:main - TimeoutError: Timed out

I could write a lot about problem beacouse I am trying to fix it last 2 days but first, does your web work with this CC2531 device?

Please answer, and thank you very much!

**Comment by mdsamdsa** [comment]
Set log level "DEBUG" for "zgwc:tcp_client" and "zgwc:proxy" in log4js.json
Run test_13_client.js and see errors

**Comment by mradmilovic** [comment]
Yes. It was a stupid mistake by me. I changed ports in config.json file, and I had to change only ip address.
